const express = require('express');
const router = express.Router();
const { authMiddleware, employeeAuth } = require('../middlewares/auth');
const { roleGuard } = require('../middlewares/roleGuard');
const { getMonthlyReport, getDashboardStats, getPunchMapData } = require('../controllers/reportController');
router.use(authMiddleware);
router.get('/dashboard', getDashboardStats);
router.get('/monthly/:employeeId', roleGuard('ADMIN', 'SUPER_ADMIN', 'MANAGER'), getMonthlyReport);
router.get('/punch-map', roleGuard('ADMIN', 'SUPER_ADMIN', 'MANAGER'), getPunchMapData);
module.exports = router;
