const express = require('express');
const router = express.Router();
const { authMiddleware, employeeAuth } = require('../middlewares/auth');
const { clockPunch, getTodayEntries, getHistory, getAllTodayEntries } = require('../controllers/timeEntryController');
router.post('/punch', employeeAuth, clockPunch);
router.get('/today', employeeAuth, getTodayEntries);
router.get('/history', employeeAuth, getHistory);
router.get('/all-today', authMiddleware, getAllTodayEntries);
router.get('/employee/:employeeId/history', authMiddleware, getHistory);
module.exports = router;
